DEFAULT_FRAME_PRED_INPUT = 4

DEFAULT_DATASET_NAME = 'ped2'
DEFAULT_DATASET_PATH = ['./dataset/' + DEFAULT_DATASET_NAME + '/']
DEFAULT_TEST_FOLDER = DEFAULT_DATASET_PATH[0] + 'testing/frames'

DEFAULT_T_LENGTH = 5
LARGE_FONT = ("Verdana", 12)

DEFAULT_DELAY = 20
